@extends('admin.layouts.master')
@section('title','Lịch sử tìm kiếm')
@section('page-title','Lịch sử tìm kiếm')
@section('content')
<div class="space-y-6">
<div class="grid gap-4 md:grid-cols-4">@foreach ([['Tổng lượt',$statistics->total ?? 0],['Không kết quả',$statistics->empty_count ?? 0],['Có click',$statistics->clicked_count ?? 0],['Từ khóa khác nhau',$statistics->unique_keywords ?? 0]] as [$label,$value])<div class="rounded-xl border bg-white p-5"><p class="text-sm text-gray-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold">{{ number_format((int)$value) }}</p></div>@endforeach</div>
<div class="grid gap-6 xl:grid-cols-2"><section class="rounded-xl border bg-white p-5"><h3 class="font-semibold">Từ khóa phổ biến</h3><div class="mt-4 space-y-2">@foreach($topKeywords as $item)<div class="flex justify-between border-b py-2"><span>{{ $item->keyword }}</span><span class="text-sm text-gray-500">{{ $item->search_count }} lượt · {{ $item->click_count }} click</span></div>@endforeach</div></section><section class="rounded-xl border bg-white p-5"><h3 class="font-semibold">Từ khóa không có kết quả</h3><div class="mt-4 space-y-2">@forelse($emptyKeywords as $item)<div class="flex justify-between border-b py-2"><span>{{ $item->keyword }}</span><span class="text-sm text-red-600">{{ $item->search_count }} lượt</span></div>@empty<p class="text-sm text-gray-500">Không có.</p>@endforelse</div></section></div>
<form method="GET" class="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-5"><input name="keyword" value="{{ request('keyword') }}" placeholder="Từ khóa..." class="rounded-lg border-gray-300 md:col-span-2"><select name="result_status" class="rounded-lg border-gray-300"><option value="">Tất cả kết quả</option><option value="has" @selected(request('result_status')==='has')>Có kết quả</option><option value="empty" @selected(request('result_status')==='empty')>Không kết quả</option></select><input type="date" name="date_from" value="{{ request('date_from') }}" class="rounded-lg border-gray-300"><input type="date" name="date_to" value="{{ request('date_to') }}" class="rounded-lg border-gray-300"><div><button class="rounded-lg bg-pink-600 px-4 py-2 text-white">Lọc</button></div></form>
<div class="overflow-hidden rounded-xl border bg-white"><div class="overflow-x-auto"><table class="min-w-full divide-y"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Từ khóa</th><th class="px-4 py-3 text-left">Người tìm</th><th class="px-4 py-3 text-left">Kết quả</th><th class="px-4 py-3 text-left">Sản phẩm click</th><th class="px-4 py-3 text-left">Thời gian</th><th></th></tr></thead><tbody class="divide-y">@forelse($histories as $history)<tr><td class="px-4 py-3 font-medium">{{ $history->keyword }}</td><td class="px-4 py-3 text-sm">{{ $history->user?->name ?? 'Khách' }}</td><td class="px-4 py-3"><span class="{{ $history->result_count ? 'text-green-600':'text-red-600' }}">{{ number_format($history->result_count) }}</span></td><td class="px-4 py-3 text-sm">{{ $history->clickedProduct?->name ?? '—' }}</td><td class="px-4 py-3 text-sm">{{ $history->created_at?->format('d/m/Y H:i') }}</td><td class="px-4 py-3"><a class="text-pink-600" href="{{ route('admin.search-histories.show',$history) }}">Chi tiết</a></td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-gray-500">Chưa có dữ liệu.</td></tr>@endforelse</tbody></table></div></div>{{ $histories->links() }}
</div>
@endsection
