@extends('admin.layouts.master')
@section('title','Quản lý nhân viên')
@section('page-title','Quản lý nhân viên')
@section('content')
<div class="space-y-6">
<div class="flex items-center justify-between"><div><h2 class="text-2xl font-bold">Nhân viên quản trị</h2><p class="text-sm text-gray-500">Quản lý tài khoản và vai trò truy cập Admin.</p></div><a class="rounded-lg bg-pink-600 px-4 py-2 text-white" href="{{ route('admin.staff.create') }}">+ Thêm nhân viên</a></div>
@if(session('success'))<div class="rounded-lg bg-green-50 p-3 text-green-700">{{ session('success') }}</div>@endif
<div class="grid gap-4 sm:grid-cols-3">@foreach(['total'=>'Tổng nhân viên','active'=>'Đang hoạt động','blocked'=>'Đang khóa'] as $key=>$label)<div class="rounded-xl border bg-white p-5"><p class="text-sm text-gray-500">{{ $label }}</p><strong class="text-2xl">{{ number_format($statistics[$key]) }}</strong></div>@endforeach</div>
<form class="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4"><input class="rounded-lg border-gray-300" name="keyword" value="{{ request('keyword') }}" placeholder="Tên hoặc email"><select class="rounded-lg border-gray-300" name="role"><option value="">Tất cả vai trò</option>@foreach($roles as $role)<option value="{{ $role->name }}" @selected(request('role')===$role->name)>{{ $role->display_name }}</option>@endforeach</select><select class="rounded-lg border-gray-300" name="status"><option value="">Tất cả trạng thái</option>@foreach(['active'=>'Hoạt động','inactive'=>'Không hoạt động','blocked'=>'Đã khóa'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select><button class="rounded-lg bg-gray-900 px-4 py-2 text-white">Lọc</button></form>
<div class="overflow-hidden rounded-xl border bg-white"><table class="min-w-full divide-y"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Nhân viên</th><th class="px-4 py-3 text-left">Vai trò</th><th class="px-4 py-3">Trạng thái</th><th class="px-4 py-3"></th></tr></thead><tbody class="divide-y">@forelse($staff as $user)<tr><td class="px-4 py-3"><strong>{{ $user->name }}</strong><div class="text-sm text-gray-500">{{ $user->email }}</div></td><td class="px-4 py-3">{{ $user->roles->pluck('display_name')->join(', ') }}</td><td class="px-4 py-3 text-center">{{ $user->status }}</td><td class="px-4 py-3 text-right"><a class="text-pink-600" href="{{ route('admin.staff.edit',$user) }}">Sửa</a></td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-gray-500">Chưa có nhân viên.</td></tr>@endforelse</tbody></table></div>{{ $staff->links() }}
</div>
@endsection
